### ISSUE TITLE
this code is so good

### ISSUE THREAD

**Issue by imvast** [alluding/fool#1]
sike nigga this code is terrible wtf please learn pep8 u geek and why the fuck do u have so much bullshit just for a simple sniper also a very nice tip u should use black on every file before uploading

**Comment by alluding** [comment]
One, you can't code for anything, and you're a skid.

> please learn pep8 u geek

You struggle at coding, you can't properly use `typing` for your life, and you have no clue about the difference between a classmethod and staticmethod, nor do you know how to use them or understand their purposes.

> and why the fuck do u have so much bullshit just for a simple sniper also a very nice tip u should use black on every file before uploading

I do NOT care. Lower your ego, monkey man.
